name: Deploy to EC2
on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  CONTAINER_NAME: blazor-portfolio

permissions:
  id-token: write
  contents: read

jobs: 
  push: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [10.0.300]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{matrix.dotnet-version}}

      - name: Publish project
        run: |
          cd blazor-portfolio
          dotnet publish -c Release -o publish

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050093882:role/blazor-portfolio-Role-eXzB9Creurcm
          aws-region: ${{env.AWS_REGION}}

      - name: Login to ECR repo
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push image to ecr
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REPOSITORY: blazor-portfolio
          IMAGE_TAG: ${{github.sha}}
        run: |
          cd blazor-portfolio
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        env:
          REPOSITORY: blazor-portfolio
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
          EC2_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          HOSTNAME: ${{secrets.HOST}}
          USER_NAME: ${{secrets.USERNAME}}
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{env.HOSTNAME}}
          port: 22
          key: ${{env.EC2_PRIVATE_KEY}}
          username: ${{env.USER_NAME}}
          envs: REGISTRY, REPOSITORY, IMAGE_TAG, AWS_REGION, CONTAINER_NAME
          script: |
            aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $REGISTRY
            sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
            if sudo docker ps -a --format '{{.Names}}' | grep -w "$CONTAINER_NAME" > /dev/null; then
                echo "Container '$CONTAINER_NAME' exists. Stopping..."
                sudo docker stop "$CONTAINER_NAME"
                sudo docker rm "$CONTAINER_NAME"
            else
                echo "Container does not exist. No action taken."
            fi
            sudo docker run -d --name $CONTAINER_NAME -p 8080:5000 -e ASPNETCORE_ENVIRONMENT=Production -e ASPNETCORE_URLS=http://0.0.0.0:5000 $REGISTRY/$REPOSITORY:$IMAGE_TAG
